name: Markdown Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli@0.32.0
      - name: Run markdownlint
        run: markdownlint "**/*.md" -c .markdownlint.json || true
      - name: Fail if issues found
        run: |
          if markdownlint "**/*.md" -c .markdownlint.json --json | jq 'length > 0' | grep -q true; then
            echo "Markdown linting issues detected";
            markdownlint "**/*.md" -c .markdownlint.json;
            exit 1;
          else
            echo "No markdownlint issues found";
          fi
